spring.application.name=dustman


server.port=9000
#.......... DB Connection


spring.datasource.username=root
spring.datasource.password=rootroot
spring.datasource.url=jdbc:mysql://localhost:3306/Dustman

spring.jpa.hibernate.ddl-auto=update
spring.output.ansi.enabled=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#spring.config.import=classpath:information.propertiesS

cloudinary.apiSecret= N1IkkDZN72MT8imtldClpoNCUfQ
cloudinary.apiKey= 676427825871499
cloudinary.cloudName= dkxei4b5s

Razorpay.Secret=XdFXq7o79O8FWFNA0wQXGOET
Razorpay.Key=rzp_test_211d0R55zEAoXB


#Oauth2
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:9000/login/oauth2/code/google
